from __future__ import annotations

from datetime import date, timedelta
from pathlib import Path

from backup_io import import_payload, ImportReport
from db import Database, now_iso
from workspace_profiles import WorkspaceProfileManager


DEMO_WORKSPACE_NAME = "Demo Workspace"


def build_demo_payload(today: date | None = None) -> dict:
    base_day = today or date.today()
    now_text = f"{base_day.isoformat()} 09:00:00"
    older_wait = f"{(base_day - timedelta(days=10)).isoformat()} 09:00:00"
    archive_stamp = f"{(base_day - timedelta(days=14)).isoformat()} 09:00:00"

    payload = {
        "format_version": 2,
        "exported_at": now_text,
        "schema_user_version": 4,
        "custom_columns": [
            {
                "name": "Energy",
                "col_type": "list",
                "created_at": now_text,
                "list_values": ["Low", "Medium", "High"],
            },
            {
                "name": "Follow-up date",
                "col_type": "date",
                "created_at": now_text,
                "list_values": [],
            },
            {
                "name": "Owner",
                "col_type": "text",
                "created_at": now_text,
                "list_values": [],
            },
        ],
        "tasks": [
            {
                "id": 1,
                "description": "Demo: Website relaunch",
                "due_date": (base_day + timedelta(days=7)).isoformat(),
                "last_update": now_text,
                "priority": 1,
                "status": "In Progress",
                "parent_id": None,
                "sort_order": 1,
                "is_collapsed": 0,
                "notes": "Project parent used to demonstrate next-action logic and child progress.",
                "archived_at": None,
                "planned_bucket": "today",
                "effort_minutes": 240,
                "actual_minutes": 90,
                "timer_started_at": None,
                "waiting_for": None,
                "recurrence_rule_id": None,
                "recurrence_origin_task_id": None,
                "is_generated_occurrence": 0,
                "reminder_at": None,
                "reminder_minutes_before": None,
                "reminder_fired_at": None,
                "custom": {},
                "tags": ["demo", "project"],
                "attachments": [],
                "dependencies": [],
            },
            {
                "id": 2,
                "description": "Finalize landing page copy",
                "due_date": base_day.isoformat(),
                "last_update": now_text,
                "priority": 1,
                "status": "In Progress",
                "parent_id": 1,
                "sort_order": 1,
                "is_collapsed": 0,
                "notes": "Active child that should appear as the next action for the relaunch project.",
                "archived_at": None,
                "planned_bucket": "today",
                "effort_minutes": 90,
                "actual_minutes": 30,
                "timer_started_at": None,
                "waiting_for": None,
                "recurrence_rule_id": None,
                "recurrence_origin_task_id": None,
                "is_generated_occurrence": 0,
                "reminder_at": f"{base_day.isoformat()} 10:30:00",
                "reminder_minutes_before": None,
                "reminder_fired_at": None,
                "custom": {"Energy": "High", "Follow-up date": (base_day + timedelta(days=1)).isoformat(), "Owner": "Mervyn"},
                "tags": ["demo", "work", "marketing"],
                "attachments": [],
                "dependencies": [],
            },
            {
                "id": 3,
                "description": "Get legal sign-off",
                "due_date": (base_day - timedelta(days=2)).isoformat(),
                "last_update": older_wait,
                "priority": 1,
                "status": "Todo",
                "parent_id": 1,
                "sort_order": 2,
                "is_collapsed": 0,
                "notes": "Waiting child used for review and stalled project checks.",
                "archived_at": None,
                "planned_bucket": "today",
                "effort_minutes": 30,
                "actual_minutes": 0,
                "timer_started_at": None,
                "waiting_for": "Legal team",
                "recurrence_rule_id": None,
                "recurrence_origin_task_id": None,
                "is_generated_occurrence": 0,
                "reminder_at": None,
                "reminder_minutes_before": None,
                "reminder_fired_at": None,
                "custom": {"Energy": "Low", "Owner": "Legal"},
                "tags": ["demo", "work", "approval"],
                "attachments": [],
                "dependencies": [],
            },
            {
                "id": 4,
                "description": "Publish final build",
                "due_date": (base_day + timedelta(days=1)).isoformat(),
                "last_update": now_text,
                "priority": 2,
                "status": "Blocked",
                "parent_id": 1,
                "sort_order": 3,
                "is_collapsed": 0,
                "notes": "Blocked child that depends on copy being finished.",
                "archived_at": None,
                "planned_bucket": "upcoming",
                "effort_minutes": 45,
                "actual_minutes": 0,
                "timer_started_at": None,
                "waiting_for": None,
                "recurrence_rule_id": None,
                "recurrence_origin_task_id": None,
                "is_generated_occurrence": 0,
                "reminder_at": None,
                "reminder_minutes_before": None,
                "reminder_fired_at": None,
                "custom": {"Energy": "Medium", "Owner": "Ops"},
                "tags": ["demo", "work", "release"],
                "attachments": [],
                "dependencies": [2],
            },
            {
                "id": 5,
                "description": "Demo: Inbox - clarify travel reimbursement",
                "due_date": None,
                "last_update": now_text,
                "priority": 3,
                "status": "Todo",
                "parent_id": None,
                "sort_order": 2,
                "is_collapsed": 0,
                "notes": "Inbox item that has not yet been processed.",
                "archived_at": None,
                "planned_bucket": "inbox",
                "effort_minutes": None,
                "actual_minutes": 0,
                "timer_started_at": None,
                "waiting_for": None,
                "recurrence_rule_id": None,
                "recurrence_origin_task_id": None,
                "is_generated_occurrence": 0,
                "reminder_at": None,
                "reminder_minutes_before": None,
                "reminder_fired_at": None,
                "custom": {"Energy": "Low", "Owner": "Finance"},
                "tags": ["demo", "admin"],
                "attachments": [],
                "dependencies": [],
            },
            {
                "id": 6,
                "description": "Demo: Weekly review",
                "due_date": base_day.isoformat(),
                "last_update": now_text,
                "priority": 2,
                "status": "Todo",
                "parent_id": None,
                "sort_order": 3,
                "is_collapsed": 0,
                "notes": "Recurring task that should appear in recurring attention review results.",
                "archived_at": None,
                "planned_bucket": "today",
                "effort_minutes": 45,
                "actual_minutes": 0,
                "timer_started_at": None,
                "waiting_for": None,
                "recurrence_rule_id": 101,
                "recurrence_origin_task_id": None,
                "is_generated_occurrence": 0,
                "reminder_at": f"{base_day.isoformat()} 16:00:00",
                "reminder_minutes_before": None,
                "reminder_fired_at": None,
                "custom": {"Energy": "Medium", "Owner": "You"},
                "tags": ["demo", "review", "recurring"],
                "attachments": [],
                "dependencies": [],
            },
            {
                "id": 7,
                "description": "Demo: Conference planning",
                "due_date": (base_day + timedelta(days=21)).isoformat(),
                "last_update": older_wait,
                "priority": 2,
                "status": "In Progress",
                "parent_id": None,
                "sort_order": 4,
                "is_collapsed": 0,
                "notes": "Project with only waiting work left, useful for stalled/blocked review categories.",
                "archived_at": None,
                "planned_bucket": "upcoming",
                "effort_minutes": 180,
                "actual_minutes": 60,
                "timer_started_at": None,
                "waiting_for": None,
                "recurrence_rule_id": None,
                "recurrence_origin_task_id": None,
                "is_generated_occurrence": 0,
                "reminder_at": None,
                "reminder_minutes_before": None,
                "reminder_fired_at": None,
                "custom": {},
                "tags": ["demo", "project", "events"],
                "attachments": [],
                "dependencies": [],
            },
            {
                "id": 8,
                "description": "Await sponsor response",
                "due_date": None,
                "last_update": older_wait,
                "priority": 3,
                "status": "Todo",
                "parent_id": 7,
                "sort_order": 1,
                "is_collapsed": 0,
                "notes": "Waiting-only child so the parent project appears stalled and blocked.",
                "archived_at": None,
                "planned_bucket": "upcoming",
                "effort_minutes": 20,
                "actual_minutes": 0,
                "timer_started_at": None,
                "waiting_for": "Sponsor team",
                "recurrence_rule_id": None,
                "recurrence_origin_task_id": None,
                "is_generated_occurrence": 0,
                "reminder_at": None,
                "reminder_minutes_before": None,
                "reminder_fired_at": None,
                "custom": {"Energy": "Low", "Owner": "Events"},
                "tags": ["demo", "events", "waiting"],
                "attachments": [],
                "dependencies": [],
            },
            {
                "id": 9,
                "description": "Demo: Someday - redesign office storage",
                "due_date": None,
                "last_update": now_text,
                "priority": 5,
                "status": "Todo",
                "parent_id": None,
                "sort_order": 5,
                "is_collapsed": 0,
                "notes": "Someday task used for perspective and planning-bucket examples.",
                "archived_at": None,
                "planned_bucket": "someday",
                "effort_minutes": None,
                "actual_minutes": 0,
                "timer_started_at": None,
                "waiting_for": None,
                "recurrence_rule_id": None,
                "recurrence_origin_task_id": None,
                "is_generated_occurrence": 0,
                "reminder_at": None,
                "reminder_minutes_before": None,
                "reminder_fired_at": None,
                "custom": {"Energy": "Low", "Owner": "Facilities"},
                "tags": ["demo", "someday"],
                "attachments": [],
                "dependencies": [],
            },
            {
                "id": 10,
                "description": "Demo: Completed - February review",
                "due_date": (base_day - timedelta(days=1)).isoformat(),
                "last_update": f"{(base_day - timedelta(days=1)).isoformat()} 17:00:00",
                "priority": 2,
                "status": "Done",
                "parent_id": None,
                "sort_order": 6,
                "is_collapsed": 0,
                "notes": "Completed item for history, analytics, and completed perspective examples.",
                "archived_at": None,
                "planned_bucket": "upcoming",
                "effort_minutes": 30,
                "actual_minutes": 30,
                "timer_started_at": None,
                "waiting_for": None,
                "recurrence_rule_id": None,
                "recurrence_origin_task_id": None,
                "is_generated_occurrence": 0,
                "reminder_at": None,
                "reminder_minutes_before": None,
                "reminder_fired_at": None,
                "custom": {"Energy": "Medium", "Owner": "You"},
                "tags": ["demo", "review"],
                "attachments": [],
                "dependencies": [],
            },
            {
                "id": 11,
                "description": "Demo: Archived - old migration checklist",
                "due_date": (base_day - timedelta(days=30)).isoformat(),
                "last_update": archive_stamp,
                "priority": 4,
                "status": "Done",
                "parent_id": None,
                "sort_order": 7,
                "is_collapsed": 0,
                "notes": "Archived example for archive browser and restore demonstrations.",
                "archived_at": archive_stamp,
                "planned_bucket": "upcoming",
                "effort_minutes": 15,
                "actual_minutes": 15,
                "timer_started_at": None,
                "waiting_for": None,
                "recurrence_rule_id": None,
                "recurrence_origin_task_id": None,
                "is_generated_occurrence": 0,
                "reminder_at": None,
                "reminder_minutes_before": None,
                "reminder_fired_at": None,
                "custom": {"Energy": "Low", "Owner": "Ops"},
                "tags": ["demo", "archive"],
                "attachments": [],
                "dependencies": [],
            },
            {
                "id": 12,
                "description": "Demo: Vendor invoice follow-up",
                "due_date": (base_day - timedelta(days=1)).isoformat(),
                "last_update": older_wait,
                "priority": 2,
                "status": "Todo",
                "parent_id": None,
                "sort_order": 8,
                "is_collapsed": 0,
                "notes": "Overdue task that also carries a tag used by saved views.",
                "archived_at": None,
                "planned_bucket": "today",
                "effort_minutes": 20,
                "actual_minutes": 0,
                "timer_started_at": None,
                "waiting_for": None,
                "recurrence_rule_id": None,
                "recurrence_origin_task_id": None,
                "is_generated_occurrence": 0,
                "reminder_at": None,
                "reminder_minutes_before": None,
                "reminder_fired_at": None,
                "custom": {"Energy": "Medium", "Owner": "Finance"},
                "tags": ["demo", "work", "finance"],
                "attachments": [],
                "dependencies": [],
            },
        ],
        "recurrence_rules": [
            {
                "id": 101,
                "task_id": 6,
                "frequency": "weekly",
                "create_next_on_done": 1,
                "is_active": 1,
                "created_at": now_text,
                "updated_at": now_text,
            }
        ],
        "saved_filter_views": [
            {
                "name": "Demo: Overdue work",
                "state": {
                    "search_text": "tag:work due<today",
                    "filter_panel": {},
                    "perspective": "all",
                    "sort_mode": "manual",
                },
                "created_at": now_text,
                "updated_at": now_text,
            },
            {
                "name": "Demo: Inbox triage",
                "state": {
                    "search_text": "",
                    "filter_panel": {"hide_done": True},
                    "perspective": "inbox",
                    "sort_mode": "manual",
                },
                "created_at": now_text,
                "updated_at": now_text,
            },
            {
                "name": "Demo: Waiting",
                "state": {
                    "search_text": "is:waiting",
                    "filter_panel": {},
                    "perspective": "all",
                    "sort_mode": "manual",
                },
                "created_at": now_text,
                "updated_at": now_text,
            },
        ],
        "templates": [
            {
                "name": "Demo: Meeting follow-up",
                "payload": {
                    "tasks": [
                        {
                            "id": 1,
                            "description": "Follow up with {owner} on {project_name}",
                            "due_date": "{due_date}",
                            "priority": 2,
                            "status": "Todo",
                            "parent_id": None,
                            "sort_order": 1,
                            "is_collapsed": 0,
                            "notes": "Demo template showing placeholder replacement.",
                            "archived_at": None,
                            "planned_bucket": "inbox",
                            "effort_minutes": None,
                            "actual_minutes": 0,
                            "timer_started_at": None,
                            "waiting_for": None,
                            "recurrence_rule_id": None,
                            "recurrence_origin_task_id": None,
                            "is_generated_occurrence": 0,
                            "reminder_at": None,
                            "reminder_minutes_before": None,
                            "reminder_fired_at": None,
                            "custom": {"Owner": "{owner}", "Energy": "Medium"},
                            "tags": ["demo", "followup"],
                            "attachments": [],
                            "dependencies": [],
                        },
                        {
                            "id": 2,
                            "description": "Send summary to {owner}",
                            "due_date": "{due_date}",
                            "priority": 3,
                            "status": "Todo",
                            "parent_id": 1,
                            "sort_order": 1,
                            "is_collapsed": 0,
                            "notes": "",
                            "archived_at": None,
                            "planned_bucket": "today",
                            "effort_minutes": None,
                            "actual_minutes": 0,
                            "timer_started_at": None,
                            "waiting_for": None,
                            "recurrence_rule_id": None,
                            "recurrence_origin_task_id": None,
                            "is_generated_occurrence": 0,
                            "reminder_at": None,
                            "reminder_minutes_before": None,
                            "reminder_fired_at": None,
                            "custom": {"Owner": "{owner}"},
                            "tags": ["demo", "followup"],
                            "attachments": [],
                            "dependencies": [],
                        },
                    ]
                },
                "created_at": now_text,
                "updated_at": now_text,
            }
        ],
    }
    return payload


def populate_demo_database(db: Database, today: date | None = None) -> dict:
    if db.fetch_tasks():
        raise ValueError("Demo data can only be loaded into an empty database.")

    payload = build_demo_payload(today=today)
    existing_columns = {str(col.get("name") or "") for col in db.fetch_custom_columns()}
    for column in payload.get("custom_columns") or []:
        name = str(column.get("name") or "").strip()
        if not name or name in existing_columns:
            continue
        db.add_custom_column(name, str(column.get("col_type") or "text"), list(column.get("list_values") or []))
        existing_columns.add(name)

    report: ImportReport = import_payload(None, payload, db)
    rows = db.fetch_tasks()
    archived = sum(1 for row in rows if str(row.get("archived_at") or "").strip())
    recurring = sum(1 for row in rows if row.get("recurrence"))
    return {
        "imported_tasks": int(report.imported_tasks or 0),
        "created_columns": int(report.created_columns or 0),
        "task_count": len(rows),
        "archived_count": archived,
        "saved_view_count": len(db.list_saved_filter_views()),
        "template_count": len(db.list_templates()),
        "recurring_count": recurring,
    }


def create_demo_workspace(
    manager: WorkspaceProfileManager,
    *,
    today: date | None = None,
    name: str = DEMO_WORKSPACE_NAME,
) -> dict:
    record = manager.create_workspace(str(name or DEMO_WORKSPACE_NAME), inherit_current_state=True)
    db_path = str(record.get("db_path") or "")
    db = Database(db_path)
    try:
        summary = populate_demo_database(db, today=today)
    except Exception:
        try:
            db.conn.close()
        except Exception:
            pass
        try:
            manager.remove_workspace(str(record.get("id") or ""))
        except Exception:
            pass
        try:
            Path(db_path).unlink(missing_ok=True)
        except Exception:
            pass
        raise
    finally:
        try:
            db.conn.close()
        except Exception:
            pass
    return {"workspace": record, "summary": summary}
